### ISSUE TITLE
It should be possible for the application to play audio files

### ISSUE THREAD

**Issue by ntoll** [pyscript/pypercard#24]
This ought to be specified as a default audio file to play when a `Card` instance is rendered, or as a simple call within a transition function. It should be possible to flag if the audio file continues until completion or stops when the current `Card` transitions to another one. It should also be possible to say if the audio file loops or not.

**Comment by WebReflection** [comment]
Just adding some context: audio is an [HTML well defined behavior and element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio) and there are security constraints around it, most notably:
  * you need an explicit user click event (or other events) to grant the ability to reproduce audio
  * controls are provided by the browser vendor by default and are suggested to be used instead of re-creating ours (but we could)
  * *autoplay* is an accessibility hazard and must be considered [very carefully](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio#attributes)

**Comment by ntoll** [comment]
Fixed by 9cc4c5615826d218bb47ab595b342e7ea9d22cb6

Example app here: https://pyscript.github.io/pypercard/examples/loosey_goosey/
